# Generated by Django 4.0.4 on 2022-04-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='f',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='answer',
            name='x',
            field=models.CharField(max_length=1000),
        ),
    ]
